### PR TITLE
Fix multi dispose scheduler and timer

### LINKED ISSUE #798: Calling dispose twice on DisposableTimer raises a exception
## The problem

Calling dispose twice on DisposableTimer raises a exception. According to microsoft documentation a dispose implementation should allow this: https://learn.microsoft.com/en-us/dotnet/api/system.idisposable.dispose?redirectedfrom=MSDN&view=net-7.0#System_IDisposable_Dispose

## Environment

- NetDaemon release with the issue: 22.44.0
- Last working NetDaemon release (if known):
- Operating environment (Home assistant Add-on/Docker/Dev setup): Dev setup
- Link to integration documentation on our website:

## Link to or paste code that causes the issue

```c#
        var timer = new DisposableTimer(CancellationToken.None);
        timer.Dispose();
        timer.Dispose();
```

## Traceback/Error logs

```txt
System.ObjectDisposedException: The CancellationTokenSource has been disposed.
   at System.Threading.CancellationTokenSource.Cancel()
   at NetDaemon.Extensions.Scheduler.DisposableTimer.Dispose()
```

### PR DESCRIPTION
**Pull request by Barsonax**
## Proposed change

Check before running the dispose code if the object has already been disposed previously. If so skip the code.

Also added a simple unit test to check if its possible to dispose twice without exception.

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (which adds functionality to an existing integration)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Additional information

- This PR fixes or closes issue: fixes #798 
- This PR is related to issue:
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [x] Local tests pass. **Your PR cannot be merged unless tests pass**
- [x] There is no commented out code in this PR.
- [ ] I have followed the [development checklist][dev-checklist]
- [x] The code compiles without warnings (code quality chek)
- [x] Tests have been added to verify that the new code works.

### CODE REVIEW

File: src/Extensions/NetDaemon.Extensions.Scheduling/DisposableTimer.cs [hunk 1]
```diff
@@ -10,6 +10,8 @@ public sealed class DisposableTimer : IDisposable
 {
```
Comment (FrankBakkerNl) [inline src/Extensions/NetDaemon.Extensions.Scheduling/DisposableTimer.cs:10]: I think this class should have been internal actually

File: src/Extensions/NetDaemon.Extensions.Scheduling.Tests/Scheduling/DisposableTimerTest.cs [hunk 2]
```diff
@@ -0,0 +1,17 @@
+﻿using System.Threading;
+using NetDaemon.Extensions.Scheduler;
+using Xunit;
+
+namespace NetDaemon.Extensions.Scheduling.Tests;
+
+public class DisposableTimerTest
+{
+    [Fact]
```
Comment (FrankBakkerNl) [inline src/Extensions/NetDaemon.Extensions.Scheduling.Tests/Scheduling/DisposableTimerTest.cs:9]: Suggestion: 
Because this is really a helper class that should be internal it does not seem to deserve its own test class. You could move this test to SchedulerExtensionTest.SchedulePeriodicStopsAfterDisposeOfSubscriber() and dispose the result of disposable.RunEvery there twice

**Review by FrankBakkerNl — APPROVED** [review]
