### PR TITLE
Fix disable Admin API using setting

### LINKED ISSUE #176: web api hardcoded to port 5000
PROBLEM: The new web API controller is hardcoded to run on port 5000. And the new admin UI is hardcoded to http://127.0.0.1:5000/api/apps. Unfortunately this conflicts with my configuration (running in a docker container on my Synology NAS which already has the admin UI on port 5000)

SOLUTION: Allow overriding the port via env variable like the rest of the configuration. e.g. NETDAEMON__WEBAPIPORT=5001

## 

Happy to put together a PR if you want it

### PR DESCRIPTION
**Pull request by helto4real**
## Proposed change

- Disable API by using NetDaemon.Admin = false or NETDAEMON__ADMIN=false env. 
- Able to change port with normal ASPNETCORE_URLS environment var. (Not recommended)

## Type of change

- [ ] Dependency upgrade
- [] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (which adds functionality to an existing integration)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [x] Code quality improvements to existing code or addition of tests

## Additional information

- This PR fixes or closes issue: fixes #176 
- This PR is related to issue:
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [x] Local tests pass. **Your PR cannot be merged unless tests pass**
- [x] There is no commented out code in this PR.
- [x] I have followed the [development checklist][dev-checklist]
- [x] The code compiles without warnings (code quality chek)
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [x] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/net-daemon/docs

### CODE REVIEW

File: src/DaemonRunner/DaemonRunner/NetDaemonExtensions.cs [hunk 1]
```diff
@@ -16,16 +16,15 @@ public static class NetDaemonExtensions
...
             return hostBuilder.ConfigureServices((context, services) =>
             {
                 services.Configure<HomeAssistantSettings>(context.Configuration.GetSection("HomeAssistant"));
                 services.Configure<NetDaemonSettings>(context.Configuration.GetSection("NetDaemon"));
-
             }).ConfigureWebHostDefaults(webbuilder =>
             {
                 webbuilder.UseKestrel(options =>
                 {
-                    options.Listen(IPAddress.Loopback, 5000); //HTTP port
```
Comment (ludeeus) [inline src/DaemonRunner/DaemonRunner/NetDaemonExtensions.cs:28]: Where did this got moved to?

Comment (helto4real) [reply src/DaemonRunner/DaemonRunner/NetDaemonExtensions.cs:28]: it is default 5000 and we can use the DOTNET_URLS standard to change if we want to but we dont
